### ISSUE TITLE
Not linkify links with russian simbols

### ISSUE THREAD

**Issue by arsenichev** [SoapBox/linkifyjs#100]
If linkify string "Test string and url to wiki https://ru.wikipedia.org/wiki/Список_птиц,_занесённых_в_Красную_книгу_России" lib dont find this link.

**Comment by cawa-93** [comment]
Confirm. Returns a string
```
Test string and url to wiki <a href="https://ru.wikipedia.org/wiki/" class="linkified" target="_blank">https://ru.wikipedia.org/wiki/</a>Список_птиц,_занесённых_в_Красную_книгу_России
```
Using linkifyjs#2.0.0-beta.7

**Comment by arsenichev** [comment]
Yes, this url returned https://ru.wikipedia.org/wiki/ but its not very good. Full link realy is https://ru.wikipedia.org/wiki/Список_птиц,_занесённых_в_Красную_книгу_России

**Comment by denya-vs** [comment]
Hi, what about this issue? This plugin is awesome, but I can`t use it for cyrillic domain or urls.
If you haven`t time, can you tell me how to fix it?

**Comment by fcarreiro** [comment]
Interesting, the problem also happens with other non-ascii symbols, when they are in the last position:
<img width="716" alt="screen shot 2016-07-08 at 00 33 29" src="https://cloud.githubusercontent.com/assets/499245/16672035/a0d06482-44a3-11e6-811f-3141a72f1c4c.png">

**Comment by fcarreiro** [comment]
@nfrasser what is the general UTF support of this library? I couldn't find it :)

**Comment by nfrasser** [comment]
@fcarreiro the non-ASCII symbol issue was a long-running bug. It was just fixed in the latest release.

The sample URLs included here should all be working (Russian symbols are now supported in the query string), but there are still issues with international domain names - see #92. I'm closing this one off in favour of that.
