### ISSUE TITLE
Add `local` to tlds.js

### ISSUE THREAD

**Issue by mbojey** [SoapBox/linkifyjs#101]
Would allow linkifying of links like `http://neon.myCompany.local:8000/www/Project/latest`

**Comment by nfrasser** [comment]
Sure thing, just has to be added to [this file](https://github.com/SoapBox/linkifyjs/blob/master/tlds.js) in alphabetical order.

**Comment by mbojey** [comment]
So it looks like you are using `local` as a domain as well.  I guess that means that it can't be used as a TLD?  Is there anyway it can be used as both?

**Comment by nfrasser** [comment]
I would update the test to make `local` a TLD. Relevant line is [here](https://github.com/SoapBox/linkifyjs/blob/d4ddb56d8c03bc4e41cc70fd61b45e6fd4aca11a/test/spec/linkify/core/scanner-test.js#L66). The `DOMAIN` should be changed to `TLD`.

I apologize for the delay on this, was having trouble accessing Travis earlier to see the issue.

**Comment by nfrasser** [comment]
Fixed in #102
