### ISSUE TITLE
Add custom TLDs as an option

### ISSUE THREAD

**Issue by herbit** [SoapBox/linkifyjs#104]
In my company we use in the local invironment custom TLDs like ".ads" and ".dev". How about adding an interface to add custom TLDs as an option?

**Comment by EugenMayer** [comment]
beside that, why is the tlds.js only used for linkify.amd.js - this would be a way to compile linkify with custom tld support, but as linkify.js does not include this, it would be helpfull to have either a option or a similar implementation
