### ISSUE TITLE
linking hashtags

### ISSUE THREAD

**Issue by staminna** [SoapBox/linkifyjs#117]
Hi

Linkifyjs is successfully creating links from strings using linkifyStr(string) , but the hashtags get linked locally, such as http://localhost/#hashtag

How can I make them link to Twitter's own domain?

thanks

**Comment by nfrasser** [comment]
You can use the [`formatHref`](http://soapbox.github.io/linkifyjs/docs/options.html#formathref) option:

```js
'This repo is #rad'.linkify({
  formatHref: function (value, type) {
    if (type === 'hashtag') {
      value = 'https://twitter.com/hashtag/' + value.substring(1);
    }
    return value;
  }
});
```
