### ISSUE TITLE
disallowing linking texts without protocol or www

### ISSUE THREAD

**Issue by scazzy** [SoapBox/linkifyjs#118]
the script linkifies all text with a valid extension, which is creating some trouble for me.
eg: will help you heal.do this everyday...
I missed space after "heal." and it converted it into a link.

Any option to allow only texts starting with protocols (http(s)://) or "www." be linkfied?

**Comment by nfrasser** [comment]
`.do` is actually a [valid top-level domain](https://en.wikipedia.org/wiki/.do)

To prevent links links without protocols from being detected, use the [`validate`](http://soapbox.github.io/linkifyjs/docs/options.html#validate) option.
