### ISSUE TITLE
Update TLD listing to support all ICANN TLDs

### ISSUE THREAD

**Issue by herrevilkitten** [SoapBox/linkifyjs#120]
The official ICANN TLD listing (https://data.iana.org/TLD/tlds-alpha-by-domain.txt) has a lot of additional TLDs that are not supported by linkify.  This causes links such as http://unfiltered.news/#/2016/03/18 to not be linkified.  Assuming that all that is required is that `tlds.js` be updated, I will submit a pull request later.

**Comment by nfrasser** [comment]
Thanks for the fix! The PR has been merged, it'll be included in the next release.
