### ISSUE TITLE
Problem with linkify hashtag plugin

### ISSUE THREAD

**Issue by stanleycyang** [SoapBox/linkifyjs#122]
I am writing code to turn hashtags to links.

I put in the following code ( from the docs ):

```js
var linkify = require('linkifyjs');
require('linkifyjs/plugin/hashtag')(linkify); // optional
var linkifyHtml = require('linkifyjs/html');
```

I get the error:

```
error given was: TypeError: Cannot read property 'scanner' of undefined
```

Any ideas what is causing this?

**Comment by nfrasser** [comment]
There was a typo in the docs, which I've just fixed. It should be 

```js
require('linkifyjs/plugins/hashtag')(linkify);
``` 

`plugins` not `plugin`.  Let me know if that works.

**Comment by stanleycyang** [comment]
Works! Thanks!
