### ISSUE TITLE
Linkify HTML messes up at end of tag

### ISSUE THREAD

**Issue by haydenbleasel** [SoapBox/linkifyjs#123]
Using `require('linkifyjs/html')`

Input:

```
<p>This is an example HTML document for a GitHub (github.com) project called linkify: https://github.com/SoapBox/linkifyjs</p>
```

Outputs:

```
[ { type: 'url', value: 'http://example.com/', href: 'http://example.com/' },
  { type: 'url', value: 'github.com', href: 'http://github.com' },
  { type: 'url', value: 'https://github.com/SoapBox/linkifyjs</p', href: 'https://github.com/SoapBox/linkifyjs</p' } ]
```

I don't think it picks up on end tags correctly, hence:

```
https://github.com/SoapBox/linkifyjs</p
```

**Comment by nfrasser** [comment]
It looks like you're using `linkify.find` to get that output. The core linkify library, which contains the `find` method, does not currently have support for HTML input, and there are no plans to add it in the future. 

However, the [`linkify-html`](http://soapbox.github.io/linkifyjs/docs/linkify-html.html) interface _can_ handle HTML input and will properly convert URL strings inside tags into `'<a>...</a>'` strings.

Here are my suggestions

1. Use the `linkify-html` interface to convert strings of HTML, or
2. Run a strip tags algorithm ([example](https://css-tricks.com/snippets/javascript/strip-html-tags-in-javascript/)) on your text before running `linkify.find` on it.

Hope that helps.

**Comment by haydenbleasel** [comment]
Hi @nfrasser, no worries and thanks for filling me in. One last question - can I pass an entire HTML document to `linkifyjs/html`? I currently have a multi-line string but `linkifyhtml(html, {})` returns nothing.
