### ISSUE TITLE
Only Linkify plain text and already linked text

### ISSUE THREAD

**Issue by rlaferla** [SoapBox/linkifyjs#134]
e.g.

`Linkify the following URL: <a href="https://www.google.com">https://www.google.com</a>
`

should not change the output because the link is already present

`Linkify the following URL: <a href="https://www.google.com">https://www.google.com</a>
`

but

`Linkify the following URL: https://www.google.com
`

should output:

`Linkify the following URL: <a href="https://www.google.com">https://www.google.com</a>`

**Comment by nfrasser** [comment]
Could you give a more specific code example? Are you using `linkify-string`?

**Comment by nfrasser** [comment]
Double-checked both `linkify-string` and `linkify-html`, and they are both working as intended with the given text. Please use `linkify-html` if you're parsing strings that already have HTML in them.

**Comment by rlaferla** [comment]
I'm using the demo on the Github project page.

**Comment by nfrasser** [comment]
Yes, the behaviour is correct. By default, linkify assumes it's given plain text. This is mostly to prevent you from shooting yourself in the foot when displaying unvalidated user-generated text (e.g., if the user inputs the text `<script>alert("Hacked!");</script>`)

If you absolutely need to linkify text that has HTML in it (text that has been validated to ensure it cannot execute malicious code), use [`linkify-html`](http://soapbox.github.io/linkifyjs/docs/linkify-html.html)
