### ISSUE TITLE
No dist in npm linkifyjs 

### ISSUE THREAD

**Issue by Geczy** [SoapBox/linkifyjs#135]
Most NPM packages come with a precompiled min / regular js files, but linkifyjs does not

/dist/linkifyjs.min.js
/dist/linkifyjs.js

For example

**Comment by Geczy** [comment]
Need a standalone linkify + jquery file

**Comment by nfrasser** [comment]
I realize this is a common use case, but NPM really shouldn't be used as a browser package manager unless you're using something like Browserify with it. That said, I can definitely add it in (bearing in mind that it'll triple the size of the NPM payload).

In the mean time, you can [download the precompiled zip from the latest release](https://github.com/SoapBox/linkifyjs/releases), or consider [Bower](http://bower.io/) for package management instead.

**Comment by Geczy** [comment]
You're right, I should be using Browserify, thanks! I'm using that now and that solves my issue. My mistake for having a bad workflow!
