### ISSUE TITLE
Query string after domain name

### ISSUE THREAD

**Issue by denya-vs** [SoapBox/linkifyjs#139]
Linkify do not recognize query string in url like this:
http://test.com?asd=asd
![proof](http://img.netpeak.ua/denya/d2016051812%3A51%3A06.png)

**Comment by nfrasser** [comment]
The website was using an older version of linkify, which has been updated to fully recognize the specified link.

Just note that `test.com?asd=asd` isn't a completely valid web URL, you actually also need a slash between `com` and `?`, i.e., `test.com/?asd=asd`

**Comment by jpagand** [comment]
@nfrasser I cannot find any mention of a slash needed between `com` and `?` on the [URI RFC](https://tools.ietf.org/html/rfc3986#section-3.4)


Moreover linkify do not recognize the same case as above but without the `http://` protocol

![f98he](https://cloud.githubusercontent.com/assets/2401332/17473022/77dadbfc-5d4e-11e6-8f17-f4b46986ed75.PNG)

**Comment by defraz** [comment]
@jpagand This may help [URI Syntax Components](https://tools.ietf.org/html/rfc3986#section-3). Even when empty the path segment must begin with '/'.

**Comment by nfrasser** [comment]
Furthermore, Linkify greedily treats anything that begins with`http://`as a URL. This is a feature to support custom hostnames and internal networks. You'll find that most browsers will do the same.

**Comment by jpagand** [comment]
Ok, thank you for those details.

But, is it plan to recognize `test.com?a=b` in future version?
