### ISSUE TITLE
linkify-element throws Invalid DOM Node type on <object>s

### ISSUE THREAD

**Issue by Farow** [SoapBox/linkifyjs#140]
Full error message: `Cannot linkify [object HTMLObjectElement] - Invalid DOM Node type`

Demo: https://jsfiddle.net/g6xwbtt4/1/

**Comment by nfrasser** [comment]
Issue is [here](https://github.com/SoapBox/linkifyjs/blob/3ddac753998fc9c6ea11e02b89e67a121efb9517/src/linkify-element.js#L93). The `typeof` check should be removed. Fix coming soon.
