### ISSUE TITLE
Stop mutating the prototype

### ISSUE THREAD

**Issue by DoctorBlue** [SoapBox/linkifyjs#142]
The browsers command it!

> Warning: Mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create.

Usually, if Firefox warns you about something, you want a pretty good reason to ignore that warning. I think it's worth considering a fix for this, unless it's too much work. I don't expect it to take a very high priority, but that's fine. Just something I think ought to be on the backlog :)

**Comment by nfrasser** [comment]
This warning is actually caused by the generated class inheritance code from [Babel](http://babeljs.io/)

**Comment by moll** [comment]
Just stumbled upon this, too, and looking forward to seeing this removed.
