### ISSUE TITLE
ignoreTags - images

### ISSUE THREAD

**Issue by nullatmidnight** [SoapBox/linkifyjs#159]
Not too sure if this is a bug or just not implemented yet but the image tag doesn't work when adding it to the ignoreTags array.

**Comment by nfrasser** [comment]
I'm not sure what you're trying to do here. Can you include some example code?

Specifying an `ignoreTags` option means linkify will not try to find URLs in elements that can never have links in them, such as `script` tags and `select` inputs. `img` tags are usually self-closing and cannot have content, so this shouldn't be an issue. `ignoreTags` will also not strip out image tags for you.

**Comment by nullatmidnight** [comment]
Sure. So I pass a string through using `linkifyStr(text, options);` with options for `ignoreTags` and to convert new lines into breaks.

If the string contains an img tag without a URL reference:

"`Hey, this is a pic <img src="logo.png">`" it will correctly display the image and text. However, if I the string contains a URL to the image location:



> Hey, this is a pic <img src="http://www.google.com/logo.png">

 it will convert to:

> Hey, this is a pic " class="linkified" target="_blank">http://www.google.com/logo.png">

**Comment by nfrasser** [comment]
The `ignoreTags` option is only supported by the [element, jquery, and html](http://soapbox.github.io/linkifyjs/docs/options.html#ignoretags) interfaces (not the string one). `linkifyStr` is only meant for plain text strings and will escape HTML entities.

You should use [`linkifyHtml`](http://soapbox.github.io/linkifyjs/docs/linkify-html.html) instead.
