### ISSUE TITLE
Add option to truncate long URLs

### ISSUE THREAD

**Issue by euangoddard** [SoapBox/linkifyjs#16]
It would be helpful to be able to pass an option to limit the number characters of the output link text inside the <a> element to prevent overflow issue when people paste very long link.

If this is not possible, a post-linkification hook would be useful so that a 3rd party could perform such an action.

**Comment by nfrasser** [comment]
Fixed in #51, with the `format` option. 

Example:

```js
$('p').linkify({
  format: function (value, type) { 
    // value is the link, type is 'url', 'email', etc.
    if (type === 'url' && value.length > 50) { 
      value = value.slice(0, 50) + '…'; 
    } 
    return value; 
});
```

**Comment by simonferndriger** [comment]
Thank you very much!

**Comment by simonferndriger** [comment]
Not, I get the following error message `Error: Cannot linkify [object Text] - Invalid DOM Node type`

**Comment by nfrasser** [comment]
What selector are you passing in?

**Comment by deathg0d** [comment]
+1 for this feature
(Also to make links shorter and visually appealing, is there a way to hide http://, https:// and www etc?)

**Comment by nfrasser** [comment]
@deathg0d dedicated protocol and `www.` removal (though I wouldn't recommend removing `www.`) sounds like a pretty good idea. For now you can use the `format` option:

```js
$('p').linkify({
  format: function (value, type) {
    if (type === 'url') {
      value = value.replace(/^((http|ftp)s?:\/\/|:\/\/)?(www\.)?/, '');
    }
    return value;
  }
});
```

Which is available in the latest pre-release.

**Comment by nfrasser** [comment]
Closing this off as I have not been able to reproduce @simonferndriger 's error. A separate issue can be filed if the error reoccurs.
