### ISSUE TITLE
Document whether javascript: links are acceptable

### ISSUE THREAD

**Issue by kevinburke** [SoapBox/linkifyjs#160]
Browsers accept and can act on links that look like `<a href="javascript:alert('foo')">`. However allowing users to submit links that look like this can lead to XSS and/or other problems. 

It would be nice if `linkifyjs` documented somewhere that these links are _not_ parsed/translated (at least as far as I can tell). I checked the README and the options page, and neither mentioned how `javascript:` links are treated.

**Comment by nfrasser** [comment]
Currently linkify only supports links with `http(s):` and `ftp(s):` protocols. `javascript:` is not a valid protocol from the plugin's perspective, so linkify will not attempt to create `<a>` tags for text containing `javascript:`.

For more information, I've added [this doc](http://soapbox.github.io/linkifyjs/docs/caveats.html#cross-site-scripting) to go over what kind of XSS prevention this plugin provides.
