### ISSUE TITLE
import linkify from "linkifyjs" not working in webpack reactjs.

### ISSUE THREAD

**Issue by antondomratchev** [SoapBox/linkifyjs#161]
Hey guys. Thank you very much for publishing this neat library.

I am trying to get the mentions and hashtags working on my react app but I cant seem to get the hashtag or mention plugins to wokr. Based on your example posted here http://soapbox.github.io/linkifyjs/docs/2.1.html#reactjs-interface
I am importing the linkify lib and plugin and calling the plugin function on the linkify
```
import linkify from 'linkifyjs'
import hashtag from 'linkifyjs/plugins/hashtag'
hashtag(linkify)
```
I am getting the following error:
`Uncaught TypeError: Cannot read property 'scanner' of undefined hashtag @ hashtag.js:9`
which is this line
`var TT = linkify.scanner.TOKENS; // Text tokens`

this tells me that `linkifyjs` import isnt working.

I am using webpack in the project, do I need to provide a global alias for this library?

**Comment by antondomratchev** [comment]
I was able to find a solution

```
var linkify = require("linkifyjs")
import hashtag from "linkifyjs/plugins/hashtag"
import Linkify from "linkifyjs/react"
hashtag(linkify)
```

**Comment by nfrasser** [comment]
I apologize, this should have been

```js
import * as linkify from 'linkifyjs';
```

The docs have been updated with the correct declarations.
