### ISSUE TITLE
Linkify treats non-breaking space characters as part of URLs

### ISSUE THREAD

**Issue by dbkr** [SoapBox/linkifyjs#162]
Somewhere between 2.0.0-beta.4 and 2.1.0, linkify changed behaviour such that the nonbreaking space character is now treated as part of a URL. We have a particular piece of (user generated) content that has two URLs separated by a nonbreaking space which is parsed as one big URL in 2.1.0, instead of two separate ones.

I'm not sure if this change was intentional, although I imagine it would normally make more sense to treat nonbreaking spaces the same as any other spaces, which would not be treated as part of a URL.

**Comment by nfrasser** [comment]
Hey @dbkr, I can confirm that this is definitely a bug. It was introduced in #149, where the internal whitespace parsing was tweaked to use an [array of whitespace characters](https://github.com/SoapBox/linkifyjs/blob/8d21838c238946b43eb6b029f59f12464633fa80/src/linkify/core/scanner.js#L42). This array omits the non-breaking space character.

I'm issuing a fix for this now.

**Comment by nfrasser** [comment]
Fixed in v2.1.1
