### ISSUE TITLE
html_1.default is not a function

### ISSUE THREAD

**Issue by collinglass** [SoapBox/linkifyjs#176]
This error is thrown at runtime in my angular2 app with typescript. Imported with npm.

```html_1.default is not a function```

The error is gone when I change node_modules/linkifyjs/html.js file to

```module.exports = require('./lib/linkify-html');```

**Comment by nfrasser** [comment]
Apologies for the late reply. I can't reproduce this using `require('linkifyjs/html')`, though I'm not using Typescript. It looks like you might be able to fix this in your code without having to change the code from NPM by using `require('linkifyjs/lib/linkify-html')`.
