### ISSUE TITLE
Rewrite URL

### ISSUE THREAD

**Issue by ltfi** [SoapBox/linkifyjs#179]
Linkify can detect urls, but i need another thing about it. How can i rewrite url? More clearly, i wanna detect url but i wanna just replace "link" word for urls. Any idea?

www.google.com >> link

**Comment by nfrasser** [comment]
You can use the format option http://soapbox.github.io/linkifyjs/docs/options.html#format

```js
linkifyStr('www.google.com', {
  format: {
    url: function () { return 'link'; }
  }
});
```

**Comment by ltfi** [comment]
thnx.
