### ISSUE TITLE
Is there strict mode option?

### ISSUE THREAD

**Issue by artemijan** [Soapbox/linkifyjs#180]
Hello. I'm going to use your library, but before i need to know - is there a way to tell to "linkify.js" about strict search (see example below).
**For example:**
text - "I have a yard.In my memory it's like a charm." (user just forgot to insert whitespace between "." and "In")
output - "http://yard.In". 

It would be great to provide option for strict search e.g. yard.In should not be recognized in this mode as link at all - because "In" is capitalized.
Thanks.

**Comment by artemijan** [comment]
also some delimiter option is required, for example "google.com.uanhn" should not be recognized as a link at all, because it's not separated by whitespace

**Comment by nfrasser** [comment]
Hey @artemijan, this is definitely something I've seen before and we'll be looking to add it as an explicit option in the future.

As a temporary workaround, I can suggest using the [`validate`](http://soapbox.github.io/linkifyjs/docs/options.html#validate) option. You can prevent links that don't begin with a protocol from being detected (see the included sample code) or use a more clever regex that detects capitals in the domains.

**Comment by nfrasser** [comment]
Use the `validate` options
