### ISSUE TITLE
Can't entirely remove target attribute from regular URL?

### ISSUE THREAD

**Issue by VirtualWolf** [SoapBox/linkifyjs#187]
I have a function that includes this:

    if (context) {
        context = context.linkify({
            formatHref: {
                mention: href => 'https://twitter.com' + href,
            },
            target: {
                url: null,
            },
            nl2br: true,
        });
    }

Setting `target` to `null` still results in `target="_blank"` being set in the output though. Looking at [linkify-string.js](https://github.com/SoapBox/linkifyjs/blob/master/src/linkify-string.js#L64), it seems that it's only looking for it to be set to something *other* than null, and if it's null it applies the default target? Is there any easy way to remove the target entirely (similar to #144 for linkClass)? I'm running linkify v2.1.4.

Thanks!

**Comment by nfrasser** [comment]
Fixed in v2.1.6
