### ISSUE TITLE
Rewrite link but dont wrap in href

### ISSUE THREAD

**Issue by amlwwalker** [SoapBox/linkifyjs#188]
I want to replace any url that is put in with a generic one, so if the text reads:

> Hi, please visit google.com

I want to use the linkify engine to pick up `google.com` and replace it with `example.com` (for instance).

However I don't want it to be converted to an html link, the linkifyjs engine seems really good at classifying text as a url. Is there a way to take advantage of it as a sort of find/replace? 

To de-abstract, its for an email server where the email clients can only display text, not html. I also don't want the users being able to put any link in there, as all links must point at one location (that I control), hence why I don't want `<a href="...">...</a>` inserted.

Thanks

**Comment by nfrasser** [comment]
Hey @amlwwalker, I'd recommend looking into the [`linkify.tokenize`](http://soapbox.github.io/linkifyjs/docs/linkify.html#linkifytokenize-str) function. It generally isn't meant to be used directly, but it should solve this particular use case.

`tokenize` returns a list of objects similar to the output of [`linkify.find`](http://soapbox.github.io/linkifyjs/docs/linkify.html#linkifyfind-str--type), but it will include all the text-only, non-URL tokens as well.

You can loop through these tokens, get their `type` property, and branch on it to either (A) use their `toString()` method to get the original text or (B) replace their text with `example.com`, or anything you choose:

```js
var result = "";
linkify.tokenize('Hi, please visit google.com').forEach(token => {
  if (token.type === 'url') {
    result += 'example.com';
  } else {
    result += token.toString();
  }
});

return result;
```

See [`linkify-string`](https://github.com/SoapBox/linkifyjs/blob/6e4b1eddc280a4a53ad825ffbdd9a7ea46160ed5/src/linkify-string.js#L32-L77) for a more detailed example. I hope that helps.

**Comment by itayganor** [comment]
@nfrasser 
Sorry for opening this old issue again, but since you mentioned `linkify-string` as a resource for examples, I have a question:
Do `token.isLink` and `token.type === 'url'` come together? What's the difference between the two?

**Comment by nfrasser** [comment]
Hi @itayganor, apologies for the delay. `token.type` could be `text`, `url` or `email` (or `hashtag` or `mention`, if you use those plugins). `token.isLink` will be true for all those types except `text`.
