### ISSUE TITLE
Links have mandatory domain extension

### ISSUE THREAD

**Issue by lucamerolla** [SoapBox/linkifyjs#19]
For example, if we use the IP address we have some weird behaviour.

This does not work:
http://127.0.0.1/test/home.action

this, instead, works:
http://127.0.0.1.com/test/home.action

**Comment by nfrasser** [comment]
Partially fixed: domain extension is no longer required, but IP addresses do not work yet. A plugin will be added for this sometime in the future.

**Comment by r4lex** [comment]
Hi there, I just tried the following link in the demo https://github/SoapBox/linkifyjs/ and it doesn't make it clickable. Was the change in 2.0 only specifically for http://localhost/?
