### ISSUE TITLE
Linkify-react with HTML

### ISSUE THREAD

**Issue by jrock17** [SoapBox/linkifyjs#190]
I was able to get the react version of Linkify working great, but it spits out HTML tags which then show up on on render. Normally I would show HTML in React using:

`<p dangerouslySetInnerHTML={{__html: content}}></p>`

But I can't figure out how to get the results of the linkify-react component into content (it shows as an object.

Anyone know how to handle?

**Comment by nfrasser** [comment]
The Linkify React component won't play nicely with `dangerouslySetInnerHTML`. Since you have the HTML string, I'd recommend using [`linkify-html`](http://soapbox.github.io/linkifyjs/docs/linkify-html.html) instead:

```jsx
<p dangerouslySetInnerHTML={{__html: linkifyHtml(content)}}></p>
```
