### ISSUE TITLE
Linkify changes "<hmm" to "<hmm>".

### ISSUE THREAD

**Issue by hifall** [SoapBox/linkifyjs#191]
We are developing a chat app, which relays participant entered messages. We use linkify to convert any link text in user entered messages to <a> tags.

But in some cases, linkify's behavior is not what we desired. For example, it returns "&lt;hmm&gt;" for "<hmm". Since text like "<hmm" can be normal text, and we don't want linkify to convert it.

I am not able to find any option to force this behavior. Any idea?

**Comment by nfrasser** [comment]
Hey @hifall, you're using `linkify-html`, correct? This looks like a bug with [`simple-html-tokenizer`](https://github.com/tildeio/simple-html-tokenizer), which is used by linkify to properly parse HTML. It's incorrectly recognizing `<hmm`as an opening tag.

I'm going to try updating to the latest version of the tokenizer to see if that fixes it.

**Comment by nfrasser** [comment]
Alternatively, if your app does not need support for HTML input (e.g., when user enters a formatted message with `<b>` or `<i>` for bold and italics), you should definitely use [`linkify-string`](http://soapbox.github.io/linkifyjs/docs/linkify-string.html), the plaintext string interface. This will fix your problem.

**Comment by hifall** [comment]
@nfrasser Yes I was using linkify-html, thanks for pointing that out. Switching to linkify-string as suggested seems to fix this issue.

Thanks!
