### ISSUE TITLE
Strange behavior regarding html tag text 

### ISSUE THREAD

**Issue by ReguluSpica** [Soapbox/linkifyjs#192]
While `<a href="www.google.com">www.yahoo.com</a>` will return perfectly as 
&lt;a href="<a href="http://www.google.com" class="linkified" target="_blank">www.google.com</a>"&gt;<a href="http://www.yahoo.com" class="linkified" target="_blank">www.yahoo.com</a>&lt;/a&gt;

`<a href="http://www.google.com">www.yahoo.com</a>` goes strangely and show 
<a href="<a href="http://www.google.com&quot;&gt;www.yahoo.com&lt;/a&gt;" class="linkified" target="_blank">http://www.google.com">www.yahoo.com</a&gt;</a>

This might be a minor problem, but it's bugging me hard.

**Comment by nfrasser** [comment]
This is a symptom of using the `http://` protocol. When `http://` is present, linkify will interpret *everything* that follows as a URL, up to the next whitespace character or another appropriate delimiter. This is mainly to support custom internal protocols such as `.dev` top-level domains. Browsers like Chrome do this as well (e.g., when differentiating between URLs and search requests).

I'd consider this a minor issue, but pull requests are welcome!

**Comment by nfrasser** [comment]
I suggest using [linkify-html](https://soapbox.github.io/linkifyjs/docs/linkify-html.html) if your input string has existing HTML to avoid this issue
