### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16.

### ISSUE THREAD

**Issue by f0urfingeredfish** [SoapBox/linkifyjs#196]
From the horse's mouth.  "React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement."

File that needs to be updated:
https://github.com/SoapBox/linkifyjs/blob/master/src/linkify-react.js#L101

thank you!

**Comment by jkudish** [comment]
Any update on this?

**Comment by nfrasser** [comment]
Fixed in v2.1.6
