### ISSUE TITLE
Incorporating Fancybox?

### ISSUE THREAD

**Issue by stevekitch** [SoapBox/linkifyjs#202]
Just wondering if there is a way of incorporating the Fancybox code in the link so that Youtube videos open in a light box rather than going to the full page?

A plain text link www.youtube.com/watch?v=_sI_Ps7JSEk would become: 
"<a **data-fancybox** href="https://www.youtube.com/watch?v=_sI_Ps7JSEk">www.youtube.com/watch?v=_sI_Ps7JSEk</a>"

No problem if not, it works really well anyway!

**Comment by nfrasser** [comment]
Depending on which interface you use, include an `attributes` option with an empty `data-fancybox`

e.g., 

```js
function getLinkAttributes(url, type) {
  if (url.includes('youtube.com/watch')) {
    return { 'data-fancybox': ''}
  }
  return {}
}

// Using jQuery plugin
$('#selector').linkify({
  attributes: getLinkAttributes
})

// Using HTML text plugin
linkifyHtml(data, {
  attributes: getLinkAttributes
})
```

http://soapbox.github.io/linkifyjs/docs/options.html#attributes
