### ISSUE TITLE
Problem with mentions on server side of application

### ISSUE THREAD

**Issue by oshnix** [SoapBox/linkifyjs#207]
Hello guys, I have a bit strange problem and I want to ask for your advice.
I have a function that should parse text before displaying it to user:
```javascript
if(post.description){
	post.description = linkifyHtml(post.description, {
		nl2br: true
	})
}
return post;
```
And I'm using mention plugin in order to parse mentions.     
But a string like this
`Some text with link https://github.com and mention @github`
Turns into
`Some text with link  <a href="https://github.com" class="linkified" target="_blank">https://github.com</a> and mention @github`    
on server side of my application (I'm using Vue.js to render my app)    
It does work on user side, though. Moreover, If i'm inserting something like this:    
`console.log(linkify.find(post.description))` I get this mention:    
```
[ { type: 'url', value: 'https://github.com', href: 'https://github.com' },
{ type: 'mention', value: '@github', href: '/github' } ]
```
And I don't understand how it's possible.

I tried to reproduce this but script with same code being run by node works fine to.    
If there's some possibility to look into how linkifyHtml works to find links?

P.S.    
I firstly thought that there's some problem with imports and tried to replace them with require just in top of my function like this:
```javascript
var linkify = require('linkifyjs');
var linkifyHtml = require('linkifyjs/html');
var plugin = require('linkifyjs/plugins/mention');
plugin(linkify);
```
But this had no effect

**Comment by oshnix** [comment]
After a little research I found that problem is somewhere in `parser.run` function, because with the same input it gives different results for server side `linkify.find` and `linkifyHTML`    
I am not sure, but maybe the problem is connected with different `S_START` state in parser.    
When mentions aren't parsed it's property `j [array]` consists of 8 objects and in right cases - of 9    
If someone tells me about possible configurations that can affect parser behaviour I'll continue my research

**Comment by nfrasser** [comment]
@oshnix my apologies for taking so long to get back. Were you able to find a solution? I'm not sure how to go about reproducing this. Can you put together a sample repository that shows the bug?
