### ISSUE TITLE
wrong linkifying for @mail

### ISSUE THREAD

**Issue by shevdi** [SoapBox/linkifyjs#208]
linkifyjs doesn't recognize properly email containing `@mail`. If it's `mail@mail.com` or `mail@cmail.com` there's no mistake. But if `mail@mailc.com`, `mail@mail ` part will become text and `c.com` part will become usual http link

**Comment by bennyn** [comment]
**This issue does not seem to be fixed.** I just tried to render "support@mailfence.com" on the [Linkify test page](http://soapbox.github.io/linkifyjs/) and it fails:

![image](https://user-images.githubusercontent.com/469989/33270368-1c186cf0-d384-11e7-944d-68db90f51ad1.png)

**Comment by izadmehr** [comment]
@nfrasser Could you please release the 2.1.6. So, this bug will be fixed.
