### ISSUE TITLE
Emoji '<3' getting ripped off with linkify-html

### ISSUE THREAD

**Issue by hugoazevedosoares** [Soapbox/linkifyjs#222]
Any string which contains some heart emojis '<3' loses them when linkify-html is used.

Eg1: 'I <3 you' turns into 'I  \<you\>';
Eg2: '<3<3<3' turns into ''.

**Comment by nfrasser** [comment]
I'd recommend encoding the `<` as `&lt;` before passing it to linkify-html

**Comment by nfrasser** [comment]
Alternatively use [linkify-string](https://soapbox.github.io/linkifyjs/docs/linkify-string.html) instead of linkify-html
