### ISSUE TITLE
Add option rel

### ISSUE THREAD

**Issue by Qeneke** [SoapBox/linkifyjs#226]
It must be rel as well as target in options
ex. `<Linkify options={{ target: { url: '_blank', hashtag: '' }, rel: { url: 'nofollow', hashtag: '' } }} />`

**Comment by nfrasser** [comment]
You can do this by specifying an `attributes` option with a function that returns the required attributes based on the given `type` parameter:

```jsx
<Linkify options={{ attributes: (href, type) => type === 'url' ? { rel: 'nofollow' } : {} }} />
```
