### ISSUE TITLE
Doesnt work with typescript/Angular 5

### ISSUE THREAD

**Issue by MTRNord** [SoapBox/linkifyjs#227]
Hi I used this in typescript and wanted to add plugins like the Documentation for ES6 explains. But using It I get the following build error:

```
ERROR in src/app/tweet-list/tweet-list.component.ts(18,10): error TS2708: Cannot use namespace 'linkifyM' as a value.
src/app/tweet-list/tweet-list.component.ts(19,10): error TS2708: Cannot use namespace 'linkifyM' as a value.
```

The problematic lines can be found in here: https://github.com/SocialNetworkNews/SocialNetworkNews-Web/blob/dabfb2d71b1d72929be916ef95ba99d3f4cd8af2/src/app/tweet-list/tweet-list.component.ts#L15-L19

**Comment by MTRNord** [comment]
@nazarkryp oh thanks for the snippet. I guess my Pipe is just to simple. Didn't expect that to work.

**Comment by Ileksa** [comment]
What should I install to get typescript code that works? I've installed linkifyjs, but compiler wants to see declaration file .d.ts.
