### ISSUE TITLE
Hashtags don't have target="_blank"

### ISSUE THREAD

**Issue by anna-osipova** [SoapBox/linkifyjs#230]
Works fine for normal urls, but not for hashtags.
Can be reproduced in this example: https://runkit.com/embed/9ylawvengxrl

**Comment by nfrasser** [comment]
This is by design, as generally hashtags open on the same page. If you want targets for all link types,
specify an explicit [`target` option](http://soapbox.github.io/linkifyjs/docs/options.html#target)

e.g., 

```js
linkifyStr('#hashtag', { target: '_blank' })
```
