### ISSUE TITLE
& converted to &amp; (NOT using JQuery)

### ISSUE THREAD

**Issue by mysublife** [Soapbox/linkifyjs#236]
Hi, thanks for the great library.

I am just having an issue with some auto formatting performed by linkify. I am using only linkify.min.js & linkify-string.min.js

This is what I get from Chrome devtools:
![linkify](https://user-images.githubusercontent.com/29241648/39775328-865c2842-52cb-11e8-8f67-526d134fc28a.PNG)

Is there an option to prevent this?

Thank you

**Comment by nfrasser** [comment]
There is no option to prevent this. Can you explain why this is problem?
