### ISSUE TITLE
linkifyjs can't be installed

### ISSUE THREAD

**Issue by kaungmyatlwin** [SoapBox/linkifyjs#237]
Hello I'm trying to install linkify with npm but seems like the repo doesn't exist on npm. Here is my command.

`npm install linkifyjs --save`

Here is the error shown.

```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'minizlib'
```

I think you guys pulled it out of npm. If so why?

**Comment by nfrasser** [comment]
Worked fine for me. Check your network settings or clear your cache. 
```
> npm install linkifyjs --save
+ linkifyjs@2.1.6
added 21 packages in 2.288s
```

The missing package in question is `minizlib` (likely a sub-dependency), not `linkifyjs`. If you're still have issues, I suggest reporting it with them: https://github.com/isaacs/minizlib

**Comment by kaungmyatlwin** [comment]
I think you should add this in the docs as an option.
