### ISSUE TITLE
Exclude .bablerc from npm package

### ISSUE THREAD

**Issue by a-golovanov** [SoapBox/linkifyjs#240]
File `.bablerc` is included in npm package even though it's not needed. This may lead to `Couldn't find preset "es2015" relative to directory ".../node_modules/linkifyjs"` error in projects that use `babel`, but do not use `babel-preset-es2015`. For example, react native projects use `babel-preset-es2015-node` instead.

**Comment by nfrasser** [comment]
Fixed in v2.1.7
