### ISSUE TITLE
Links with special character not working

### ISSUE THREAD

**Issue by velmurugansp** [Soapbox/linkifyjs#242]
**Given Text:** https://docs.google.com/spreadsheets/d/edit#gid=sdfdsfsd

**Expected Result:** `<a href="https://docs.google.com/spreadsheets/d/edit#gid=sdfdsfsd" target="_blank">https://docs.google.com/spreadsheets/d/edit#gid=sdfdsfsd</a>`

**Actual Result:*<a href="https://docs.google.com/spreadsheets/d/edit&lt;span class=">#gid=sdfdsfsd" class="linkified" target="_blank"&gt;https://docs.google.com/spreadsheets/d/edit<span class="purple_color">#gid</span>=sdfdsfsd</a>* 

**What is the Bug?** : It converts all occurrences of  `#grid` into `<span class="purple_color">#gid</span>`

**Comment by nfrasser** [comment]
Cannot reproduce using the input box at http://soapbox.github.io/linkifyjs/

Can you make a pull request with a failing test case?
