### ISSUE TITLE
linkifyHTML has problems with '<' character not being part of a tag

### ISSUE THREAD

**Issue by tapia** [Soapbox/linkifyjs#246]
Currently, linkifyHtml doesn't handle correctly the '<' character when it's not part of a tag. It transforms `I <3 you` into `I <you>`, and this:

```
Hey, how are you? >.< Nice to meet you
```

into this:

```
Hey, how are you? >.<nice to="" meet="" you="">
```

This is probably related to #191 (a bug in simple-html-tokenizer), but it was closed without really solving the problem.

**Comment by waqasd4int** [comment]
+1
 I'd be very interested in any progress on this too.

**Comment by seeratawan01** [comment]
@waqasasif9292 you can use [html-entities](https://github.com/mdevils/html-entities) before linkifying the text to encode characters

**Comment by waqasasif9292** [comment]
@seeratawan01 it worked, thanks a lot

**Comment by nfrasser** [comment]
My final word on this is the if you expect un-escaped HTML characters in your input, you should use [linkify-string](https://soapbox.github.io/linkifyjs/docs/linkify-string.html), not linkify-html
