### ISSUE TITLE
Update React Event Handler Docs To Be More Helpful

### ISSUE THREAD

**Issue by cranberryofdoom** [Soapbox/linkifyjs#248]
Hey! A small suggestion to your React Docs:
https://soapbox.github.io/linkifyjs/docs/linkify-react.html#events

```
let linkProps = {
  onClick: () => confirm('Are you sure you want to leave this page')
};
```

This is a great example of what most folks want-- a confirmation modal making sure that the user actually did want to leave the page. However, with this implementation, the 'Cancel' button triggers the default event anyway and will open the link.

```
let linkProps = {
  onClick: (event) => {
    if (!confirm('Are you sure you want to leave this page')) {
       event.preventDefault()
    }
  }
};
```
I'd love to change it so that your example covers the actual use case of canceling navigation when the "Cancel" button is pressed! I wasn't sure where I could suggest changes to your docs, so I'm posting it here. Let me know if this is something you'd like a PR (and where I can go to make those changes)-- I'd be happy to make one.

**Comment by nfrasser** [comment]
Hi @cranberryofdoom, great suggestion; pull requests are definitely welcome! 

The docs for this repo are on the `gh-pages` branch. The React Events docs are at [docs/linkify-react.md](https://github.com/SoapBox/linkifyjs/blob/gh-pages/docs/linkify-react.md#events).
