### ISSUE TITLE
Project Description Says "Zero-Dependency" - Seems to be Incorrect

### ISSUE THREAD

**Issue by mleone** [SoapBox/linkifyjs#252]
![image](https://user-images.githubusercontent.com/9357/48790985-a1f61300-ecbe-11e8-8a62-e5d3d05a71b7.png)

![image](https://user-images.githubusercontent.com/9357/48791040-c3ef9580-ecbe-11e8-8be6-b933d18616e5.png)

Edit: I understand these are in optionalDependencies, but that still makes for a much more complex yarn/npm dependency graph. Not trying to be pedantic but I don't think that's the same as "zero-dependency." Am I off-base here?

**Comment by nfrasser** [comment]
Noted, README now advises to install with "ignore optional" flags.

**Comment by chrisjbrown** [comment]
I tried installing with
`yarn add --ignore-optional linkifyjs`

which adds linkify without adding the optional dependencies.
however when I do something like remove `node_modules` and then run `yarn` again

It then installs linkify with the optional dependencies
am i supposed to run `yarn --ignore-optional` everytime I run yarn?
