### ISSUE TITLE
Ability to ignore/exclude certain mentions

### ISSUE THREAD

**Issue by onassar** [SoapBox/linkifyjs#256]
Hi there -
Love the mentions feature (and hello from Toronto :P)
I'm running into a slight issue and hoping there's an API based fix for it.

I have some text that I want to convert to GitHub mentions, however every now and then, users will use the string ` ... blah blah @font-face blah blah ...` and I want to ignore the `@font-face` "mention", since it means something different in this context.

Is it possible to define an array of mentions to ignore?
Thanks!

**Comment by nfrasser** [comment]
This is possible with the [`validate` option](https://soapbox.github.io/linkifyjs/docs/options.html#validate):

```js
require('linkifyjs/plugins/mention')(require('linkifyjs'))
const linkifyStr = require('linkifyjs/string')

linkifyStr('@onassar @font-face', {
  validate: {
    mention: value => !['@font-face'].includes(value)
  }
}) // '<a href="/onassar" class="linkified">@onassar</a> @font-face'
```

Hello from Kitchener!

**Comment by onassar** [comment]
Great thanks @nfrasser :)
