### ISSUE TITLE
Disable mailto links?

### ISSUE THREAD

**Issue by grahamking** [SoapBox/linkifyjs#263]
Is it possible to disable linkifying mailto links, so that it only links http/https?

**Comment by nfrasser** [comment]
Use the `[validate` option](https://soapbox.github.io/linkifyjs/docs/options.html#validate)

```js
let options = {
  validate: { email: false }
}
```

**Comment by rmcsharry** [comment]
@nfrasser this option appears to be broken in v4.0.2
