### ISSUE TITLE
Jquery validate option being ignored

### ISSUE THREAD

**Issue by sorce-squires** [SoapBox/linkifyjs#267]
Out of the box this does what we need except for mentions, I am currently writing code to not linkify a mention in certain situations. The validate function is running (getting console log output) but the true/false value passed back in jquery land is being ignored and linkifying anyway:
`$pi.linkify({
				formatHref: function (href, type) {
					if (type === 'mention') {
					href = '/sorce/beacon/profile' + href;;
					}
					return href;
				},
				validate:{ 
					mention: function(link, type){
						console.log(link);
						return link == "@admin";
					}
				}
			});
            $pi.linkify();`

Files used:
Jquery - 3.1.0
latest version of the following files as of 11am 20/March/2019:
linkify.js
linkify-jquery.js
linkify-plugin-mention.js

Any hints or tips is greatly appreciated as I have followed the documentation as far as I can see.

**Comment by nfrasser** [comment]
Validate functions should return `true` if you want a link, and `false` if you don't. This Node.js code works for me (internal option processing code is identical in Node v.s. jQuery)

```js
const linkify = require('linkifyjs')
const linkifyStr = require("linkifyjs/string")
require('linkifyjs/plugins/mention')(linkify)

let result = linkifyStr('Hello @admin @non-admin', { 
    formatHref: function (href, type) { 
        if (type === 'mention') { 
            href = '/sorce/beacon/profile' + href;; 
        } return href; 
    }, 
    validate:{ 
        mention: function (link, type) { 
            console.log(link); 
            return link == "@admin"; 
        } 
    } 
})

console.log(result)
```

Output:

```
"@admin"
"@non-admin"
"Hello <a href=\"/sorce/beacon/profile/admin\" class=\"linkified\">@admin</a> @non-admin"
```

Did you mean to write `link != "@admin"`?

**Comment by sorce-squires** [comment]
Thanks for the quick response! :) I have been trying both != and == but no change to the output.

good to know it's working somewhere, for clarity:
The content on the page is:
`
@admin
blah blah
@user
`
For this page @user should be the only one linkified but both are still being linkified. :(

**Comment by sorce-squires** [comment]
Apologies I just found its down to our implementation else where, many thanks @nfrasser for answering the question!
