### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lgbm** [Soapbox/linkifyjs#274]
Failing with certain URLs:

https://xxxxxxxx/checkout/mYNzvfHeWEtz8Ac-NwobrYPPyjLRur-d7mdYq1T3N3c,
https://xxxxxxxx/checkout/mYNzvfHeWEtz8Ac-NwobrYPPyjLRur-d7mdYq1T3N3c.

chars in the final of url "," "." is the issue.

**Comment by nfrasser** [comment]
Excluding the . and , at the end of a URL is the expected behaviour
