### ISSUE TITLE
linkifyjs/react breaks in Jest tests with Preact project

### ISSUE THREAD

**Issue by raderj89** [SoapBox/linkifyjs#276]
Not sure if this is Jest or preact-specific, but I just added Linkifyjs to my preact project, and I'm using preact-compat to enable using React libraries. It works fine in development, but when I try to run the test suite, it fails with this:

```  
● Test suite failed to run

    TypeError: Cannot redefine property: type
        at Function.defineProperty (<anonymous>)
    > 1 | import Linkify from 'linkifyjs/react';
```

The stack trace points to preact-compat/src/index.js:60 which has:

```javascript
Object.defineProperty(VNode.prototype, 'type', {
	get() {
		return this.nodeName;
	},
	set(v) {
		this.nodeName = v;
	},
	configurable: true
});
```

Full stacktrace:

```
      at node_modules/preact-compat/src/index.js:60:8
      at node_modules/preact-compat/dist/preact-compat.js:2:82
      at Object.<anonymous> (node_modules/preact-compat/dist/preact-compat.js:5:2)
      at Object.<anonymous> (node_modules/linkifyjs/lib/linkify-react.js:5:14)
      at Object.<anonymous> (node_modules/linkifyjs/react.js:1:45)
```

**Comment by raderj89** [comment]
solved https://stackoverflow.com/questions/56974998/preact-compat-incompatibility-in-jest-tests/57102515#57102515

**Comment by adamchenwei** [comment]
@raderj89 no its not solved
samething happening on latest react with latest jest. Would u take a look? https://github.com/Soapbox/linkifyjs/issues/333
