### ISSUE TITLE
Use peerDependencies instead of optionalDependencies to be truely zero-dependency

### ISSUE THREAD

**Issue by G-Rath** [Soapbox/linkifyjs#281]
[`optionalDependencies` are for when you want `npm` to continue installing if a dependency cannot be found or fails to install.](https://docs.npmjs.com/files/package.json#optionaldependencies)

[`peerDependencies` are for when you want to express the compatibility of your package with a host tool or library, while not necessarily doing a require of this host.](https://docs.npmjs.com/files/package.json#peerdependencies)

This is the reason why as soon you do *any* form of install w/o the `--no-optional` flag, it'll install both `react` and `jquery` :)

This is in part a continuing of #252

**Comment by antoniopacheco** [comment]
Agree, and this will solve an issue for duplicate reacts, while using react hooks:
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by antoniopacheco** [comment]
Here is the PR for this issue:
https://github.com/SoapBox/linkifyjs/pull/282

**Comment by nfrasser** [comment]
Fixed in #282
