### ISSUE TITLE
Validate option not working in React

### ISSUE THREAD

**Issue by shwetas** [Soapbox/linkifyjs#283]
I am trying to use validate function to only linkify if url is from certain domain or has http.

<Linkify properties ={{validate: {
                                        url: function (text) {
                                           return /^(http|ftp)s?:\/\//.test(text) || text.slice(0,3) === 'www';
                                          }
                                     }}}>{elem.text}
</Linkify>

I tried with <Likify options={{options}} as well but none of them seems to work.
Other properties like target and style works fine 
<Linkify key={index} properties={{target: '_blank', style: {color: 'red', fontWeight: 'bold'}}}>

Really appreciate any suggestion.
Thanks.

**Comment by nfrasser** [comment]
It seems be working for me, see sample code: https://codesandbox.io/s/zealous-merkle-qodpv
Note that you should be using `<Linkify options={{ validate: (text) => ... }}>`

Did you find the problem? Feel free to reopen if not.
