### ISSUE TITLE
Linkify-html 2.1 in IE

### ISSUE THREAD

**Issue by mea-alexanm** [Soapbox/linkifyjs#285]
Hello,

when trying to use linkify-html 2.1 with IE11 the following error is thrown:
Object does not support property or method 'default'. On Firefox and Chrome it works.

Any ideas?

Thx
Markus

**Comment by nfrasser** [comment]
Hi Markus, our automated browsers testing suite runs IE11 tests on every commit - everything appears to work with no errors in the latest v2.1.9. Be sure to use `dist/linkify.js` instead of the the Node-compatible files in the root directory for IE11 support.

Can you send me the code to reproduce this issue? Please reopen once you do.

**Comment by q329895** [comment]
Hello,

I am including linkify via package,json in an angular application. No idea what version is used there :-(.
I have updated to Version 2.1.9 now. Upon installing I get a warning that it needs react 0.14.0 and react-dom 0.14.0. I guess this should be issue, but is not nice.

My code looks like this:
 
public linkify(cell: any) {
    const iconHtml = this._externalLinkHtml;
    const options = {
      format: function (value, type) {
        if (type === 'url') {
          return iconHtml;
        }
        return value;
      }
    };

    try {
      return linkifyHtml(cell.displayValue, options);
    }
    catch {
      return cell.displayValue;
    }
  }

BR
Markus

**Comment by nfrasser** [comment]
Can you also show me how you are importing linkify into your code? E.g. show me your `<script>` tag or `require` statement

**Comment by q329895** [comment]
Hello,

I am using import { linkifyHtml } from 'linkifyjs/html';
Not sure how to import it from 'dist/linikfy';

Thx
Markus

**Comment by nfrasser** [comment]
> Not sure how to import it from 'dist/linikfy';

You can add the browser-ready packaged version of linkify to your HTML ([download here](https://github.com/SoapBox/linkifyjs/releases/download/v2.1.9/linkifyjs.zip))

```html
<script src="dist/linkify.js"></script>
<script src="dist/linkify-html.js"></script>
```

If you're using ES modules (the `import` statement), you should be using `import linkifyHtml from 'linkifyjs/html'`, as per [the docs](https://soapbox.github.io/linkifyjs/docs/linkify-html.html). 

When you are use ES modules, you to configure Angular to compile your code with support for older browsers (linkify uses the `default` keyword as property names, which I suspect is not valid in IE11).  [Building your Angular app in production mode may help with this](https://angular.io/start/deployment).

> Upon installing I get a warning that it needs react 0.14.0 and react-dom 0.14.0. I guess this should be issue, but is not nice.

React is optional, you don't need to have either of these installed. You may ignore the warning.
