### ISSUE TITLE
linkifyjs/html getting crashed when using mixed characters

### ISSUE THREAD

**Issue by Gowthaman-Ganesan** [Soapbox/linkifyjs#293]
linkifyjs/html is getting crashed when using numerical characters in between chinese alphabets.

Content: 這禮拜是我們新的循環 (3/23-4/19), 我將於這週日給 Jeffrey 補課，並且我們會在這期間選另外一個可以上課的日期。

Sending this line from FB to our text editor and parsing the message with linkifyjs/html is making the page crashed

**Comment by Arrow-Green** [comment]
It will be nice if I get an update regarding this issue. Thanks in advance
