### ISSUE TITLE
Custom text inside tag

### ISSUE THREAD

**Issue by simonepizzamiglio** [Soapbox/linkifyjs#294]
Hi,

is here a way to put a custom text inside the link tag? I'd like the output to look like this:

`click <href ="https://github.com/">here</a> to visit our website`
click [here](https://github.com/) to visit our website

**Comment by ultrono** [comment]
This is explained within the documentation: https://soapbox.github.io/linkifyjs/docs/options.html#format

So as a very simple example, to truncate the anchor tag length to 50 characters: 

```
import { truncate } from 'lodash'

let htmlString = 'some long html string'

htmlString.linkify({
  format: function (value, type) {
    return truncate(str, {
        'length': 50,
        'separator': ' '
      })
  }
})

```
