### ISSUE TITLE
Please, let the developer escape Html Tag when appropriate, it is not your responsibility

### ISSUE THREAD

**Issue by acmoune** [Soapbox/linkifyjs#304]
I am using this:

```javascript
import linkify from 'linkifyjs/string';
const content = linkify(someTextVar, {...});
```

And I am getting this as result:

`&lt;p&gt;<a href="...">myLink</a>&lt;/p&gt;`

What I expect is this:

`<p><a href="...">myLink</a></p>`

I don't understand why you are escaping Html Tags, I think it is not your responsibility, you should just replace text with links, and let the developer decide for the rest. 

I want to set the result of `linkify(...)` as the `innerHtml` of some `div`, what should I do now ? 

I have been looking for an option to cancel that behavior, with no success so far.

Please can you advise me ?

May be I should add that I am working with ReactJS, so I can not use jQuery.

**Comment by nfrasser** [comment]
Use `import linkify from 'linkifyjs/html'` instead 
https://soapbox.github.io/linkifyjs/docs/linkify-html.html
