### ISSUE TITLE
linkify.find not working

### ISSUE THREAD

**Issue by mifas** [Soapbox/linkifyjs#306]
Why below command is not working in React app

`linkify.find('Any links to github.com here? If not, contact test@example.com');
`

**Comment by nfrasser** [comment]
Seems to be working fine

```js
const linkify = require("linkifyjs")
console.log(linkify.find('Any links to github.com here? If not, contact test@example.com'))
```

Logs this

```js
[
    {href: "http://github.com", type: "url", value: "github.com"},
    {href: "mailto:test@example.com", type: "email", value: "test@example.com"}
]
```

Can you provide more details on what you are trying to do and what code you're using to import Linkify?

**Comment by mifas** [comment]
Yes, It's working when using `require` 
https://codesandbox.io/s/jolly-tharp-de1p1?file=/src/App.js
