### ISSUE TITLE
IE 8 support

### ISSUE THREAD

**Issue by shrimalmadhur** [SoapBox/linkifyjs#32]
The library is throwing an error in IE8. Will it support IE8 in future or not?

Screenshot is attached
![linkify_error_ie8](https://cloud.githubusercontent.com/assets/642275/3342544/df1b6e20-f893-11e3-9ab0-ca1d91713c30.png)

**Comment by simkessy** [comment]
So does it work in IE8 now?

**Comment by nfrasser** [comment]
@simkessy oops, no, looks like we missed this issue for the release. Should be able to make the required fixes soon.

**Comment by nfrasser** [comment]
Fixed in #137
