### ISSUE TITLE
no instructions for React

### ISSUE THREAD

**Issue by the-wrong-guy** [Soapbox/linkifyjs#325]
Hey, how to use this React?
can you check the code below, cause it's not working as mentioned in the docs
https://codesandbox.io/s/xenodochial-zhukovsky-hkdr4?file=/src/App.js

**Comment by nfrasser** [comment]
Please read the instructions here: https://soapbox.github.io/linkifyjs/docs/linkify-react.html

You're importing the react component from the wrong place, it should be from `linkifyjs/react`:
```js
import Linkify from 'linkifyjs/react';
```
