### ISSUE TITLE
full valid mailto link returns wrong data

### ISSUE THREAD

**Issue by doubletuna** [Soapbox/linkifyjs#330]
Hi there

I'm using linkifyjs in order to parse input text and validate vs whitelist urls/emails.

when testing the following text: `<a href="mailto:someone@example.com">Send email</a>`
I get `mailto:someone@example.com">Send` as the link/email

also in the demo page:
![image](https://user-images.githubusercontent.com/44400357/118086615-efa1f100-b3cc-11eb-9c06-cceeca975802.png)

is there a workaround for this problem?

cheers

**Comment by nfrasser** [comment]
You need to use the [linkify-html interface](https://soapbox.github.io/linkifyjs/docs/linkify-html.html) to on strings that contain HTML
