### ISSUE TITLE
Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_linkifyjs.default.find')

### ISSUE THREAD

**Issue by Cerix** [Soapbox/linkifyjs#332]
I am using Linkify with React Native, but I ran into this error, does anyone know how to fix it?

[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_linkifyjs.default.find')]
....
....
at node_modules/react-native/Libraries/Components/TextInput/TextInput.js:1006:26 in _onChange
at [native code]:null in callFunctionReturnFlushedQueue

**Comment by nfrasser** [comment]
What versions of React and React Native are you using? Can you post your Babel config file, if you have one? If you can, please also send a minimal code example that reproduces the error.

**Comment by Cerix** [comment]
I'm using react native with Expo 4.4.6
   react: 16.13.1 => 16.13.1
   react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
   
I call this function onChange of an input filed: 

`function handleLinkInput(value) {
        console.log(value);
        let test = Tools.findUrl(value);
        //console.log(test);
        //setUrl(value);
    }`

`function findUrl(text) {
    let includedUrls = linkify.find(text);
    let urlFinded = includedUrls[0];
    console.log(includedUrls);
    if (includedUrls.length == 0) {
        return null;
    } else {
        return urlFinded.href;
    }
}`

Babel config is untouched from expo init
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};`

**Comment by nfrasser** [comment]
How did you import linkify? Did you do

```js
import * as linkify from 'linkifyjs'
```

or

```js
import linkify from 'linkifyjs'
```

The first version is correct

**Comment by Cerix** [comment]
> How did you import linkify? Did you do
> 
> ```js
> import * as linkify from 'linkifyjs'
> ```
> 
> or
> 
> ```js
> import linkify from 'linkifyjs'
> ```
> 
> The first version is correct

Fixed! Thanks you very much! I was using the second way
