### ISSUE TITLE
Links with ( and ) in it

### ISSUE THREAD

**Issue by Polfo** [SoapBox/linkifyjs#52]
First of all, thanks for this great useful tool and the time and effort you put in it.

I noticed a link to a page containing () does not work.
http://nl.wikipedia.org/wiki/L%27Oiseau_bleu_(theaterstuk) converts to <a href="http://nl.wikipedia.org/wiki/L%27Oiseau_bleu_" class="linkified" target="_blank">http://nl.wikipedia.org/wiki/L%27Oiseau_bleu_</a>(theaterstuk)</td> 
shown as code:
```
<a href="http://nl.wikipedia.org/wiki/L%27Oiseau_bleu_" class="linkified" target="_blank">http://nl.wikipedia.org/wiki/L%27Oiseau_bleu_</a>(theaterstuk)</td>
```

**Comment by nfrasser** [comment]
Yup, this is a known problem (see #22 ). #51 will have a fix for this.

**Comment by Polfo** [comment]
Sorry for posting this duplicate, did not notice.

**Comment by kevinrenskers** [comment]
#51 does not fully fix the problem:

The closing `)` of https://en.wikipedia.org/wiki/Company_(military_unit) is not part of the link

`<a href="https://en.wikipedia.org/wiki/Company_(military_unit" class="linkified" target="_blank">https://en.wikipedia.org/wiki/Company_(military_unit</a>)`
