### ISSUE TITLE
Is there a way to avoid certain tags?

### ISSUE THREAD

**Issue by deathg0d** [SoapBox/linkifyjs#57]
It would be nice if linkify could avoid certain tags. For example do not linkify what's inside `<code>` or `pre` tags.

**Comment by nfrasser** [comment]
Hmm, not yet, but that's a great suggestion. Thanks @deathg0d !

**Comment by saturday1** [comment]
Also not `<style>`. I tried to do this. And it works as a script, but not with `linkify()`:

```
jQuery('#container *').not( jQuery('style') ).each(function(){
    jQuery(this).linkify();
    //TESTING
    //jQuery(this).addClass('i-am-not-a-style-element');
});
```

**Comment by MrShaneH** [comment]
+ this, it would be great to be able to add an attribute or class to instruct linkify to ignore a link
e.g. 
<span data-nolinkify class="nolinkify">Everything in here that matches www.example.com is ignored</span>

**Comment by Wikunia** [comment]
I would like to use linkify on something like `<img class="emojione" alt="😄" src="//cdn.jsdelivr.net/emojione/assets/png/1F604.png?v=1.2.4"/>` which makes anything unreadable. :/
