### ISSUE TITLE
Is there a way to change target option according to url ?

### ISSUE THREAD

**Issue by VolodymyrVoloshyn** [SoapBox/linkifyjs#69]
Thanks you great plugin !
I'd like to set target= _self for some domains and _target for other ones, is there a way to do so ?
I've tried this 
target: function (type) {
//
  }
but I can't get url here.

**Comment by nfrasser** [comment]
This is currently not possible, but that's a great use case. We can definitely add this in.

**Comment by jonnywyatt** [comment]
+1! 

So we can add rel="nofollow" and target="_blank" for external URLs only

**Comment by nfrasser** [comment]
Note that the option for this is slightly different now - the callback takes parameters `(href, type)` rather than just `(type)`. 

Full docs here: http://soapbox.github.io/linkifyjs/docs/options.html

**Comment by jonnywyatt** [comment]
Impressive turnaround time thanks!
