### ISSUE TITLE
Option to require the use of a prefix

### ISSUE THREAD

**Issue by jeffijoe** [SoapBox/linkifyjs#77]
I am running text through Linkify - text that might be code.

An example:

```js
import LayoutView from 'base/layout-view';
import { props, domEvent } from 'decorators';
import tmpl from './app-header.jade';
import Radio from 'radio';
import AppHeaderViewModel from './app-header-view-model';

let auth = Radio.channel('auth'),
  shell = Radio.channel('shell'),
  clips = Radio.channel('clips');
```

Linkify highlights `Radio.channel`. It would be cool with an option to require the use of http:// or www.

**Comment by nfrasser** [comment]
Hey @jeffijoe, this is a great suggestion. We'll add it to the roadmap.

**Comment by jeffijoe** [comment]
Looking forwards to it - any workarounds till then?
