### ISSUE TITLE
Option to cut link text to N symbols

### ISSUE THREAD

**Issue by sc0rp10** [Soapbox/linkifyjs#79]
I have a link like 'https://www.google.ru/search?q=linkifyjs&oq=linkifyjs&aqs=chrome..69i57j0l2.158j0j7&sourceid=chrome&es_sm=91&ie=UTF-8
'
I linkify it and got `<a target="_blank" class="linkified" href="https://www.google.ru/search?q=linkifyjs&oq=linkifyjs&aqs=chrome..69i57j0l2.158j0j7&sourceid=chrome&es_sm=91&ie=UTF-8">https://www.google.ru/search?q=linkifyjs&oq=linkifyjs&aqs=chrome..69i57j0l2.158j0j7&sourceid=chrome&es_sm=91&ie=UTF-8</a>`. 
But in this case will be nice string like `<a target="_blank" class="linkified" href="https://www.google.ru/search?q=linkifyjs&oq=linkifyjs&aqs=chrome..69i57j0l2.158j0j7&sourceid=chrome&es_sm=91&ie=UTF-8">https://www.google.ru/search?q…</a>` (string was cut to 30 chars and followed by `&#8230;` symbol
P.S. I know that Linkify has option `format` with callback, that can do it, but IMO option is more informative and easy in use.

**Comment by willamesoares** [comment]
Implemented this in #271 
The `truncate` option has priority over the `format` function when it is used to truncate the link text.

Let me know what you think.

**Comment by nfrasser** [comment]
Released in v2.1.9
