### ISSUE TITLE
Url surrounded by Chinese chars can not be parsed properly.

### ISSUE THREAD

**Issue by ladjzero** [SoapBox/linkifyjs#82]
Thank you for your nice plugin.

Here is an issue when I startup

    input> linkifyStr('《一尺闲梦》当当网http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU')

    ouput> "《一尺闲梦》当当网<a href="http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU" class="linkified" target="_blank">http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU</a>"

《一尺闲梦》当当网<a href="http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU" class="linkified" target="_blank">http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU</a>

    expected:《一尺闲梦》当当网<a href="http://t.cn/RUy3HJN" class="linkified" target="_blank">http://t.cn/RUy3HJN</a>《一尺闲梦》亚马逊<a href="http://t.cn/RUyQxlU" class="linkified" target="_blank">http://t.cn/RUyQxlU</a>

《一尺闲梦》当当网<a href="http://t.cn/RUy3HJN" class="linkified" target="_blank">http://t.cn/RUy3HJN</a>《一尺闲梦》亚马逊<a href="http://t.cn/RUyQxlU" class="linkified" target="_blank">http://t.cn/RUyQxlU</a>

It happens to CJK context because the words are not segmented by spaces. And CJK char should NOT be one part of a valid url.

**Comment by ladjzero** [comment]
I found the Chinese chars were tokenized as `SYM`. I think these chars should be rejected. What do you think?

**Comment by nfrasser** [comment]
Hi @ladjzero , unfortunately it is impossible for this plugin to reject these characters. While Chinese characters are not actually included in the RFC specifications for URLs, real URLs do include special characters in the path or query string.

e.g.,:

http://lyricstranslate.com/en/someone-you-നിന്നെ-പോലൊരാള്‍.html

Note that even GitHub's URL parser will not do this for you:

《一尺闲梦》当当网http://t.cn/RUy3HJN《一尺闲梦》亚马逊http://t.cn/RUyQxlU

So therefore it's impossible for a regular-language parser, such as Linkify, to detect the difference between the end of the URL and the beginning of the Chinese text... **unless** there is some white space between the URL and the special characters:

《一尺闲梦》当当网 http://t.cn/RUy3HJN 《一尺闲梦》亚马逊 http://t.cn/RUyQxlU

**Comment by ladjzero** [comment]
Ok. Agree. Thank you for your comment.
