### ISSUE TITLE
Linkify existings href links to target _blank?

### ISSUE THREAD

**Issue by voidale** [SoapBox/linkifyjs#85]
It seems that linkifyjs ignores existing links is there a way to overwrite this behavior I would love to change existing links to open in a new window as well. Thanks!

**Comment by nfrasser** [comment]
Not with Linkify, but in JavaScript you can do something like this

```js
var elements = document.getElementsByTagName('a');
for (var i = 0; i < elements.length; i++) {
  elements[i].setAttribute('target', '_blank');
}
```

Or if you're using jQuery

```js
$('a').attr('target', '_blank');
```
