### ISSUE TITLE
Separate the jQuery plugin to a separate repo

### ISSUE THREAD

**Issue by Prinzhorn** [SoapBox/linkifyjs#86]
I'm confused. I've been spending more than an hour now looking for a JavaScript library which will take a plain text string, detects URLs and e-mails, turns them into links and returns a XSS safe HTML string (just like a template engine or when rendering markdown). I came across linkifyjs pretty much at the start of my journey but immediately put it away because it says "Linkify is a jQuery plugin for finding URLs in plain-text and converting them to HTML links http://soapbox.github.io/jQuery-linkify/". It took me some time and reading through StackOverflow posts to come back here just to find out that it's not any longer dependant on jQuery. Still I find the documentation extremely confusing and the textarea at the bottom of http://soapbox.github.io/linkifyjs/ accepts arbitrary HTML like script tags.

From what I understand linkifyjs is backed but a plain JavaScript implementation which does what I need. The jQuery stuff is just sugar to allow people to manipulate text nodes inside existing DOM (I assume it basically iterates over text nodes and applies the linkify/string logic). So what I'm saying is why not separate the jQuery things completely and have a clean linkifyjs project and a linkifyjs-jquery project, which depends on it. Maybe I'm not the only confused soul.

**Comment by nfrasser** [comment]
Hi @Prinzhorn, I apologize for the confusion. We have not done the best job here at conveying our goals, and I realize how frustrating it can be to try using a poorly documented plugin. I'll try my best here to address your concerns.

1. Seeing jQuery in the description was confusing. This was a relic of our pre-2.0 times; we've updated the description to remove this
2. We've updated the GitHub pages website to prevent arbitrary HTML from rendering in the example text box. This was a bug with the website code, not with Linkify.
3. The core, core Linkify experience takes a string of text and outputs an array of abstract tokens. You can choose to format these tokens in whatever way you want, including HTML. 
4. Having said that, Linkify is not yet at the stage where it is ubiquitous enough to warrant separating it from its interfaces, including String and jQuery. 
  * Many of the developers using Linkify just use it in the browser, and that is the way it was originally designed. jQuery will remain in this repository, but, as it's been for a while now, as a completely optional plugin that is not loaded unless you do so explicitly with `require('linkifyjs/jquery')`.

As we approach our 2.0 release, we'll work toward improving the documentation and making the distinction between core Linkify, the interfaces, and the plugins more clear.

Hope that answers your concerns.

**Comment by nfrasser** [comment]
As a final FYI, parsing strings of text can be accomplished with the [`linkify-string` interface](http://soapbox.github.io/linkifyjs/docs/linkify-string.html).

**Comment by Prinzhorn** [comment]
Thank you @nfrasser for your detailed explanation. I'm especially excited about number 3 because it sounds unopinionated and like it's done "right". There's just too much code out there which uses a simple regex replace for the job which is inflexible (e.g. you can't use/port the same logic in a different context like a native app, which you can with the tokens you mentioned) and often opens the door for XSS. Keep up the good work!

You may be interested to know that since opening this issue I started using linkify-string (with browserify in a react app) to power autolinking in https://www.grandma.io/ . We'll start a beta next week ;). For fun and giggles here are three screenshots of it in action.

## Reading mode:
![screenshot from 2015-11-21 11 02 44](https://cloud.githubusercontent.com/assets/679144/11317937/c4561208-903f-11e5-9e03-9ae272a25a6b.png)

## Text element is selected to change some parameters or reorder the elements:
![screenshot from 2015-11-21 11 02 49](https://cloud.githubusercontent.com/assets/679144/11317938/c4578962-903f-11e5-8b65-e7715fc6f5cd.png)

## Text editing enabled:
![screenshot from 2015-11-21 11 03 21](https://cloud.githubusercontent.com/assets/679144/11317939/c457edd0-903f-11e5-867f-7fb41503cb94.png)
