### ISSUE TITLE
Buggy output on Chrome Browser only

### ISSUE THREAD

**Issue by artsince** [SoapBox/linkifyjs#87]
I am trying to linkify the following text on linkify homepage (Number 3 on http://soapbox.github.io/linkifyjs/) and I get different results on Google Chrome (Version 46.0.2490.86 (64-bit)) and Firefox (42.0) on Ubuntu 14.04

Here's my text (in Turkish):
> Bu haritanın verileri Direniş İzleme Grubu'nun yaptığı Türkiye İşçi Eylemleri haritası ile birleşebilir esasen. https://graphcommons.com/graphs/00af1cd8-5a67-40b1-86e5-32beae436f7c?show=Comments

The result on Chrome is
```
<div id="demo-3-output" class="well demo-well">Bu haritanın verileri Direniş İzleme Grubu'nun yaptığı Türkiye İşçi Eylemleri haritası ile birleşebilir esasen. .t<a href="tps:////aphcommons.c.m/g/aphs/0/af1cd8-5a67-40b1-86e5-32beae436f7c?s?ow=Comments" class="linkified" target="_blank">tps:////aphcommons.c.m/g/aphs/0/af1cd8-5a67-40b1-86e5-32beae436f7c?s?ow=Comments</a></div>
```

The result on Firefox is:
```
<div id="demo-3-output" class="well demo-well">Bu haritanın verileri Direniş İzleme Grubu'nun yaptığı Türkiye İşçi Eylemleri haritası ile birleşebilir esasen. <a target="_blank" class="linkified" href="https://graphcommons.com/graphs/00af1cd8-5a67-40b1-86e5-32beae436f7c?show=Comments">https://graphcommons.com/graphs/00af1cd8-5a67-40b1-86e5-32beae436f7c?show=Comments</a></div>
```

Thanks a lot!

**Comment by nfrasser** [comment]
Hi @artsince, thanks for the bug report. I've issued a fix in #88, and have included it in the [latest release](https://github.com/SoapBox/linkifyjs/releases).
